data:
  root: "dataset"
  img_size: 300
  threshold: 890

model:
  name: "tf_efficientnetv2_s"
  num_classes: 92
  pretrained: true
  freeze_backbone: false
  multi_gpu: true

train:
  batch_size: 128
  num_workers: 16
  lr: 0.0004
  epochs: 10
  amp: true
  patience: 3
  checkpoint_path: "runs/best_model.pth"
  cv_checkpoint_path: "runs/cv_best_model.pth"